---
- name: "Installed package2 in ubuntu 18.04 and 20.04 (local rep)"
  hosts: ubuntu
  become: yes

  tasks:
  - name: "Installed package2"
    apt:  name=package2 state=latest

- name: "Install pckg2 in centos7.6 (local rep)"
  hosts: centos76
  become: yes

  tasks:
  - name: "Installed pckg2"
    yum: name=pckg2 state=latest
...
